apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-sso
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: argo-workflows-sso
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: /argo-workflows/oidc-client-id
    - secretKey: client-secret
      remoteRef:
        key: /argo-workflows/oidc-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-mirror-credentials
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: minio-mirror-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: sourceAccessKey
      remoteRef:
        key: /minio/root-user
    - secretKey: sourceSecretKey
      remoteRef:
        key: /minio/root-password
    - secretKey: destAccessKey
      remoteRef:
        key: /minio-truenas/access-key
    - secretKey: destSecretKey
      remoteRef:
        key: /minio-truenas/secret-key
