grafana:
  deploymentStrategy:
    type: Recreate
    rollingUpdate: null

  serviceMonitor:
    enabled: true

  plugins:
    - victoriametrics-metrics-datasource
    - victoriametrics-logs-datasource

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: ALL
      skipReload: true
      provider:
        name: default
        foldersFromFilesStructure: false

  admin:
    existingSecret: grafana-credentials
    userKey: admin-user
    passwordKey: admin-password

  persistence:
    enabled: true
    size: 5Gi
    storageClass: proxmox-lvm

  envFromSecrets:
    - name: grafana-credentials

  grafana.ini:
    server:
      root_url: https://grafana.infra.the-lab.zone
    auth:
      signout_redirect_url: https://auth.infra.the-lab.zone/logout
      oauth_auto_login: false
    auth.generic_oauth:
      enabled: true
      name: Authelia
      icon: signin
      client_id: grafana
      client_secret: $__env{GRAFANA_OAUTH_SECRET}
      scopes: openid profile email groups
      auth_url: https://auth.infra.the-lab.zone/api/oidc/authorization
      token_url: https://auth.infra.the-lab.zone/api/oidc/token
      api_url: https://auth.infra.the-lab.zone/api/oidc/userinfo
      role_attribute_path: contains(groups[*], 'admins') && 'Admin' || 'Viewer'
      role_attribute_strict: true

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: VictoriaMetrics
          type: prometheus
          url: http://vmsingle-vm-stack.monitoring.svc.cluster.local:8428
          isDefault: true
          access: proxy
        - name: VictoriaLogs
          type: victoriametrics-logs-datasource
          url: http://vlogs.monitoring.svc.cluster.local:9428
          access: proxy
        - name: VictoriaTraces
          type: jaeger
          url: http://vtraces.monitoring.svc.cluster.local:10428
          access: proxy

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
