---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: minio
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: LGTM MinIO
        property: rootUser
    - secretKey: rootPassword
      remoteRef:
        key: LGTM MinIO
        property: rootPassword
