---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: minio
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: Minio LGTM/username
    - secretKey: rootPassword
      remoteRef:
        key: Minio LGTM/password
