---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /minio/root-user
    - secretKey: rootPassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /minio/root-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-mirror-credentials
  namespace: argo-workflows
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: minio-mirror-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    # MinIO do cluster (source)
    - secretKey: sourceAccessKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /minio/root-user
    - secretKey: sourceSecretKey      
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None      
        key: /minio/root-password
    # MinIO do TrueNAS (destination)
    - secretKey: destAccessKey      
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None      
        key: /minio-truenas/access-key
    - secretKey: destSecretKey        
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None      
        key: /minio-truenas/secret-key