apiVersion: v2
name: cert-manager
version: 0.0.0
dependencies:
  - name: cert-manager
    version: "v1.19.4"
    repository: https://charts.jetstack.io
  - name: step-issuer
    version: "1.9.11"
    repository: https://smallstep.github.io/helm-charts/
