cert-manager:
  crds:
    enabled: true
    keep: true

step-issuer:
  stepClusterIssuer:
    create: true
    caUrl: https://step-ca.infra.the-lab.zone:8443
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQVdLZ0F3SUJBZ0lSQUticHFoYmdaNnNjK2J0c0dzSklia0F3Q2dZSUtvWkl6ajBFQXdJd1BERVkKTUJZR0ExVUVDaE1QVkdobElFeGhZaUJhYjI1bElFTkJNU0F3SGdZRFZRUURFeGRVYUdVZ1RHRmlJRnB2Ym1VZwpRMEVnVW05dmRDQkRRVEFlRncweU5qQXpNRFF3TVRFMU1UQmFGdzB6TmpBek1ERXdNVEUxTVRCYU1Ed3hHREFXCkJnTlZCQW9URDFSb1pTQk1ZV0lnV205dVpTQkRRVEVnTUI0R0ExVUVBeE1YVkdobElFeGhZaUJhYjI1bElFTkIKSUZKdmIzUWdRMEV3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVMyQzFFdTJPN2tBTmc4cjVCdQpsbkttd245eGVtUDltZElDNjFBS0NYOHMyV0ZlRWRIajBWTFkzc01YZDhmdklaZldTMDV5bld0WE9iY2xZY2dIClphOWpvMFV3UXpBT0JnTlZIUThCQWY4RUJBTUNBUVl3RWdZRFZSMFRBUUgvQkFnd0JnRUIvd0lCQVRBZEJnTlYKSFE0RUZnUVU5bzhGd3ZDYjJHQTNHNW9semtkU2RSTUgrbEl3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU85UQpZbDV5bHVwNlArZDFramVwM1NmZVlzMTBWVmNlenpSMU8yYm52am9kQWlFQWtDRTViTmgzOFhkZ0lSM1FuWlVFCjh5bXZiOVlmbnd6a2x0eGdad1JCS0xJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==r"
    provisioner:
      name: admin
      kid: "84wfuk6Y52HqfK3GgotUn_YeH5c3i-6uL_4B1oui5-0"
      passwordRef:
        name: step-ca-provisioner-password
        key: password
        namespace: cert-manager
