apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-assets-bucket-prefix
  namespace: traefik
spec:
  addPrefix:
    prefix: "/assets/"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: assets-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`assets.infra.the-lab.zone`)
      kind: Rule
      middlewares:
        - name: minio-assets-bucket-prefix
      services:
        - name: aistor-s3-external
          port: 9000
          scheme: http
  tls:
    secretName: infra-wildcard-tls
