apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-init-credentials
  namespace: cloudnativepg
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: db-init-credentials
    creationPolicy: Owner
  data:
    - secretKey: authelia-password
      remoteRef:
        key: "Authelia Database/password"
    - secretKey: forgejo-password
      remoteRef:
        key: "Forgejo Database/password"
