coder:
  coder:
    env:
      - name: CODER_PG_CONNECTION_URL
        valueFrom:
          secretKeyRef:
            name: coder-db-url
            key: url
      - name: CODER_ACCESS_URL
        value: "https://coder.platform.the-lab.zone"
      - name: CODER_OAUTH2_GITHUB_DEFAULT_PROVIDER_ENABLE
        value: "false"
      - name: CODER_OIDC_ISSUER_URL
        value: "https://auth.infra.the-lab.zone"
      - name: CODER_OIDC_CLIENT_ID
        value: "coder"
      - name: CODER_OIDC_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: coder-oidc-secret
            key: client-secret
      - name: CODER_OIDC_EMAIL_DOMAIN
        value: "gmail.com"
      - name: CODER_OIDC_SCOPES
        value: "openid,profile,email,groups"
      - name: CODER_OIDC_SIGN_IN_TEXT
        value: "Sign in with Authelia"
    service:
      type: ClusterIP
    serviceAccount:
      workspacePerms: true
      enableDeployments: true
      workspaceNamespaces:
        - name: coder-workspaces
    ingress:
      enable: false
