{{- if .Values.ingress.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: toolhive
  namespace: {{ .Values.runtimeNamespace.name }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      middlewares:
        - name: {{ .Values.ingress.headersMiddlewareName }}
          namespace: {{ .Values.ingress.headersMiddlewareNamespace }}
      services:
        - name: {{ .Values.ingress.serviceName }}
          port: {{ .Values.ingress.servicePort }}
  tls:
    secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
