apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustdesk-keypair
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: rustdesk-keypair
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        id_ed25519: '{{`{{ .private_key }}`}}'
        id_ed25519.pub: '{{`{{ .public_key }}`}}'
  data:
    - secretKey: private_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /rustdesk/id-ed25519
    - secretKey: public_key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /rustdesk/id-ed25519-pub
