apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: forgejo-credentials
    creationPolicy: Owner
    template:
      data:
        db-password: |-
          {{ "{{ .dbPassword }}" }}
        minio-access-key: |-
          {{ "{{ .minioAccessKey }}" }}
        minio-secret-key: |-
          {{ "{{ .minioSecretKey }}" }}
        redis-url: |-
          redis://:{{ "{{ .valkeyPassword }}" }}@valkey-primary.valkey.svc.cluster.local:6379/0
        redis-session-url: |-
          redis://:{{ "{{ .valkeyPassword }}" }}@valkey-primary.valkey.svc.cluster.local:6379/1
        redis-queue-url: |-
          redis://:{{ "{{ .valkeyPassword }}" }}@valkey-primary.valkey.svc.cluster.local:6379/2
  data:
    - secretKey: dbPassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /database/forgejo/password
    - secretKey: minioAccessKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /minio/root-user
    - secretKey: minioSecretKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /minio/root-password
    - secretKey: valkeyPassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /valkey/password
