apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: database
subsets:
  - addresses:
      - ip: {{ .Values.host | quote }}
    ports:
      - port: {{ .Values.port }}
        name: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: database
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      name: postgres
