---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-pg
  namespace: gitea
spec:
  description: "PostgreSQL cluster for Gitea"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 1

  storage:
    storageClass: truenas-nfs
    size: 20Gi

  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      encoding: UTF8

  postgresql:
    parameters:
      shared_buffers: "128MB"
      max_connections: "100"

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi
