---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitea-admin-credentials
  namespace: gitea
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: gitea-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: Gitea Admin/username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: Gitea Admin/password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
