apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          # Generator 1: every cluster with the managed label
          - clusters:
              selector:
                matchLabels:
                  lab.the-lab.zone/managed: "true"
          # Generator 2: every subdirectory under clusters/<cluster-name>/
          - git:
              repoURL: https://github.com/fwfurtado/the-lab-zone-gitops
              revision: main
              files:
                - path: "clusters/{{.name}}/**/app.yaml"
  template:
    metadata:
      name: "{{.name}}-{{.app.name}}"
      labels:
        lab.the-lab.zone/cluster: "{{.name}}"
        lab.the-lab.zone/component: "{{.app.name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "{{.app.syncWave}}"
    spec:
      project: "{{ default \"default\" .app.project }}"
      source:
        repoURL: https://github.com/fwfurtado/the-lab-zone-gitops
        targetRevision: main
        path: "{{.path.path}}"
        helm:
          releaseName: "{{ default .app.name .app.releaseName }}"
      destination:
        server: "{{.server}}"
        namespace: "{{.app.namespace}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
