apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: platform-postgres
  namespace: cloudnativepg
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  instances: 3
  enableSuperuserAccess: true

  storage:
    size: 20Gi
    storageClass: proxmox-lvm

  backup:
    barmanObjectStore:
      destinationPath: s3://postgres-backups/
      endpointURL: http://minio.minio.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: minio-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-backup-credentials
          key: ACCESS_SECRET_KEY
    retentionPolicy: "15d"

  monitoring:
    enablePodMonitor: true
