---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: platform-postgres-daily
  namespace: cloudnativepg
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  schedule: "0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: platform-postgres
