# .gitea/workflows/test-cache.yaml
# Push this to any repo with Actions enabled to test runner + cache server
name: Test Runner & Cache

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  test-cache:
    name: Validate cache round-trip
    runs-on: ubuntu-latest
    steps:
      - name: Debug environment
        run: |
          echo "=== Runner info ==="
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Arch: $RUNNER_ARCH"
          echo "Hostname: $(hostname)"

          echo ""
          echo "=== Cache environment ==="
          echo "ACTIONS_CACHE_URL: ${ACTIONS_CACHE_URL:-NOT SET}"
          echo "ACTIONS_RUNTIME_TOKEN length: ${#ACTIONS_RUNTIME_TOKEN}"

          echo ""
          echo "=== Network check ==="
          # Try to reach the cache server (strip trailing slash for curl)
          CACHE_HOST="${ACTIONS_CACHE_URL%/}"
          if [ -n "$CACHE_HOST" ]; then
            echo "Attempting to reach cache server at: $CACHE_HOST"
            curl -sf --max-time 5 "$CACHE_HOST/" && echo "Cache server reachable!" || echo "WARNING: Cache server not reachable"
          else
            echo "WARNING: ACTIONS_CACHE_URL is not set — cache server may not be configured"
          fi

      - name: Create test data
        run: |
          mkdir -p test-cache-dir
          echo "cached-at-$(date +%s)" > test-cache-dir/payload.txt
          echo "Created: $(cat test-cache-dir/payload.txt)"

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: test-cache-dir
          key: test-cache-${{ github.run_id }}

      - name: Clear local data
        run: rm -rf test-cache-dir

      - name: Restore cache
        id: restore
        uses: actions/cache/restore@v4
        with:
          path: test-cache-dir
          key: test-cache-${{ github.run_id }}

      - name: Verify round-trip
        run: |
          if [ -f test-cache-dir/payload.txt ]; then
            echo "Cache round-trip OK: $(cat test-cache-dir/payload.txt)"
          else
            echo "FAIL: cache restore did not produce expected file"
            exit 1
          fi
