---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
    creationPolicy: Owner
  data:
    - secretKey: identity_validation.reset_password.jwt.hmac.key
      remoteRef:
        key: "Authelia/jwt_secret"

    - secretKey: session.encryption.key
      remoteRef:
        key: "Authelia/session_secret"

    - secretKey: storage.encryption.key
      remoteRef:
        key: "Authelia/storage_encryption_key"

    - secretKey: storage.postgres.password.txt
      remoteRef:
        key: "Authelia Database/password"

    - secretKey: session.redis.password.txt
      remoteRef:
        key: "Valkey/password"

    - secretKey: identity_providers.oidc.hmac.key
      remoteRef:
        key: "Authelia/oidc_hmac_secret"

    - secretKey: AUTHELIA_OIDC_CLIENT_ARGOCD_SECRET
      remoteRef:
        key: "Argo CD/client-secret"

    - secretKey: AUTHELIA_OIDC_CLIENT_GRAFANA_SECRET
      remoteRef:
        key: "Grafana/oidc_client_secret"

    - secretKey: AUTHELIA_OIDC_CLIENT_FORGEJO_SECRET
      remoteRef:
        key: "Authelia/forgejo_oidc_client_secret"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-oidc-jwks
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: authelia-oidc-jwks
    creationPolicy: Owner
  data:
    - secretKey: private.pem
      remoteRef:
        key: "Authelia/oidc_jwks_private_key.pem"
