---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: authelia-secrets
    creationPolicy: Owner
  data:
    - secretKey: identity_validation.reset_password.jwt.hmac.key
      remoteRef:
        key: authelia-jwt-secret

    - secretKey: session.encryption.key
      remoteRef:
        key: authelia-session-secret

    - secretKey: storage.encryption.key
      remoteRef:
        key: authelia-storage-encryption-key

    - secretKey: storage.postgres.password.txt
      remoteRef:
        key: authelia-database-password

    - secretKey: session.redis.password.txt
      remoteRef:
        key: valkey-password

    - secretKey: identity_providers.oidc.hmac.key
      remoteRef:
        key: authelia-oidc-hmac-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-oidc-clients
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: authelia-oidc-clients
    creationPolicy: Owner
  data:
    - secretKey: AUTHELIA_OIDC_CLIENT_ARGOCD_SECRET
      remoteRef:
        key: authelia-oidc-argocd-client-secret-hashed

    - secretKey: AUTHELIA_OIDC_CLIENT_GRAFANA_SECRET
      remoteRef:
        key: authelia-oidc-grafana-client-secret-hashed

    - secretKey: AUTHELIA_OIDC_CLIENT_FORGEJO_SECRET
      remoteRef:
        key: authelia-forgejo-oidc-client-secret-hashed
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-oidc-jwks
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: authelia-oidc-jwks
    creationPolicy: Owner
  data:
    - secretKey: private.pem
      remoteRef:
        key: authelia-oidc-jwks-private-key
