---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-s3-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: velero-s3-credentials
    creationPolicy: Owner
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ "{{ .accessKeyId }}" }}
          aws_secret_access_key={{ "{{ .secretAccessKey }}" }}
  data:
    - secretKey: accessKeyId
      remoteRef:
        key: "MinIO/root-user"
    - secretKey: secretAccessKey
      remoteRef:
        key: "MinIO/root-password"
