forgejo-runner:
  replicaCount: 2
  runner:
    config:
      create: true
      existingSecret: forgejo-runner-config
      instance: http://forgejo-http.forgejo.svc.cluster.local:3000
      file:
        runner:
          capacity: 4
          fetch_interval: 30s
          envs:
            DOCKER_HOST: tcp://127.0.0.1:2376
            DOCKER_TLS_VERIFY: "1"
            DOCKER_CERT_PATH: /certs/client
          labels:
            - "ubuntu-latest:docker://registry.infra.the-lab.zone/dockerhub/library/node:22-bookworm"
            - "docker:docker://registry.infra.the-lab.zone/internal/runner-base:latest"
        container:
          network: host
          privileged: false
          options: -v /certs/client:/certs/client
          valid_volumes:
            - /certs/client

  tolerations:
    - key: "workload/forgejo-actions"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  dind:
    enabled: true
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi
