argo-cd:
  dex:
    enabled: true
  configs:
    params:
      server.insecure: true
      server.login.prompt.enabled: false
    cm:
      admin.enabled: false
      url: https://argocd.platform.the-lab.zone
      dex.config: |
        connectors:
          - type: oidc
            id: authelia
            name: Authelia
            config:
              issuer: https://auth.infra.the-lab.zone
              clientID: argocd
              clientSecret: $argocd-oidc:dex.authelia.clientSecret
              insecureEnableGroups: true
              scopes:
                - openid
                - profile
                - email
                - groups
    rbac:
      policy.default: role:readonly
      policy.csv: |
        g, sre, role:admin
      scopes: "[groups, email]"
