---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-config
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgASoI73C3895cHJ2VvIRkd5yAP2OJtcp2WuYTTEY3h6bpGT78H6oOzGrtWKbQiQ3qLxpn1nf4sWsOheNOf9IAMsdzmD43RBkPtIW5MWN0MOt9LXHyvN3gZUe/i31YqIiCTpdCUAewRt1klMMG3EExpr08a2V6d5hd5KVl1EagF29c7QgBiIZFaycmHEgNbYxaBaGlYKR8KcdAqeRNbt1RWAhnT7HAwbf6GkhxWVhz0s8B/3gctAsccClCUFRHoU8x1KBJGLeuJ2CAZiEAN0NlVXFXzSCSYG8omJk3ku/KkuAhDlAO2VcrmbUgqONz03C1nF8MS8Y2n6hvuTkix0KhoxEmiFjLroplZnhXG9qmB87Nt6pIm+BqvEMd0K0iskQGVEofKXTfo9irEbABm0aAsSYTKhVgeoVOhgfL7A4RMrPWlH2DgReqaNrs0X9WWd+Z0CsPpK6qa09BvBv3eIkoyQkwirrSAoUG7xPuCqvmjWby5lWyW7XVcr0xK67uOn4cOqPi8pNE9E8ku3ZnRWjromiUdwEJAAQzRP7OmuLR701lWIm8T4qULHRYylMP4CpDnL1PlFAhGRUQt3ce+UWFNKvweJQJstMwyb5ZI+UX/et4FMd7K9Tobu2RhsxtZ1BMoeit/FGi6KOAj7u0Q7TrAomxGzN5+ZOH2FRi1BHgUm17QC1klx1YT8B1ZOk6XJkHPXi+9dDbNvimVJl1pisW1bvrozYwRU6Des5jIyHn/gEnJ7tWDHst/NcBvvAGE7q5Gn07Q2FXZq4cyvNqS//0qQzmtGzWh43IbwJr9sUG5fvWmMkB3czgbzmj/TqStX2ksXk1epB/Wod5oHh0lzLxl0K1avPUKCIUTeXi1Pi2nUG3cA0IalT8cSF2WmlFTq9sHyBPSF3Mm2bgPR5BP3R6GUwpgF3HdojETV9YwpKPc1Ttc/UfwMDzs5ygTdyDP6q263BQ==
  template:
    metadata:
      name: proxmox-csi-config
      namespace: csi-proxmox
