---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-config
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCaZ91hVTUvcFVF2z+G+D6fIRyAIJ6mgGZ9h8FNDufNICjaQxAoVGwH22KgxIkh3q+6baVBNUN5qC0q/1ogQgrZkiLYF0EX9i5CoMIiiQYff0BHx5/UFjEFDFRSyD+QGwUCxlWSkbvT4XrYnzUuG5tPJYlbmRk61uQH5IJ9qtPlxNHiVwUR2xOO2wDFv1Agf1QrIln8Ev4sTppi4LNCWdKhoAMeANC1KZSHTmQvm05Dn04H+naeRHGGv2mYa+dwSvugQ3ONEWzgHnerMOARAur38Y4orbBY251uL/DusSu1RkzX2n0gQf3465criK7YNojRGf1twENZsV6NygNjga8BG71GO0zosDm/9seFDkUZJ/ezKrb+X9+f7xfB64IttaCFCBXo1g9jU80iOAh0fcj95Kkzw4MCRqyJvlFAHPshf2/M5baSjQe/yxlcDv+PYt4YSvy3ISj9U97Upafm1s8r69QjHoZ5Hg3fe5EblgRlrt5mW+rkkr9nOBDp3k79Qdq1R5bUqY9QhU9ViZpvt0U3MbiLxd42k+9bjlZiJ5N81AqIdsnjZ7wL8arMzJ37Cl0kjmauK879xQ6zSqz3lhA4hml/jnwEaZB8v+mTwZWwujp7PXwA1bITlC+5Ltr5NODo8Cij7k5Jx6Uakp/8bsu27vT827GDXwYkHVSDybBX8w5EAChaZwQdlQ2QubXvdb8ZOFx6YRTZsnC26QqdTdrhQIdSf9dm+TiqNX7mTA9kYfitLiMJUlXgzEVTwyq1u8hslXhLTuwL+Z/VL17V/eC0dgiFfXU0x9V523S7/0sEE/5nXYk1k8XCohUiAFcuA90/2PnjpR+pSZ2pnTfRHLCAFY5DlkNzDiYnY0rjtDrkgrKUCKAdUeZCtN1ULh3ZUGq+yXTofoQvYxHqut1QooBQvBuBR2HuZMswrPvDzLWEcKJ467NYXn8UK3u7bwCn4YI9
  template:
    metadata:
      name: proxmox-csi-config
      namespace: csi-proxmox
