---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-config
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCRx40Gcdp3YmlIOAfoceQ+tJvBcSrgaaXpqJgXhExsETf9KiUEgguUPeVLc9DZQG20URDXUoaXri3qTicvYsJBzaNosCZkbiJ1X7h4zXXJgwv03XQoa/ITDDSwXxbjMxJonE/i6aA+eW9FL4cGp4wm4ydRpCaT/XVF4Blz+BSWDddrFBSVWhvDahJl55c1s/mpK/hYdWeIPG1+TYQe/O2L7xxLADzaI4uP3kdRflgND6CBYhRL49PSQCdNaQv2o+ccvXiNLlOAIo6I6ZmOKhmqrntTFPJNLhR5zjP/W1uuo4q/uOgEQ2xJmkzS+EVsIVVbAMf89OjYYhjWxNesCteLEsn9OLLrCPBLKgXluPKKHbKRTy+wBYlEb9Rk9IrbmLnfxSBYF2oYjP7Rt9vKZffcc9pB0KvPCFA93lay/LnrgjWIrH4G9Rmn7eS6D3O8bIZ80qdmORqOqJiDIN55xb2ry3JoUxk1o1Kirmq4QJS0KKYGUbHm0o4uWoihPtH6i4RuPpsKGF1kc/S8WtmwuRO1YXn2UOKCyL8Zev/n8qqHYmm198M8fpwukI41zOhkuLo6M7Pg57D9WYmDwJtEbM/W8ewHRezY9jGA+w0rkCpnEvi7XyhR36vlEP5GqCTg9ksPQbB+0DDeSFITlm8I+vUN0OFycbtNZEVYpxAiILM4T0kb93rY7fJzLxw5J+zzZ2B8hV1j5bfdAxo/GNws7OzwSELmfkU2yUZTDISTKYZGNDKWMN9NPOOTGDEkDwaXjfaznygkdrAF4nL8QWg5kqUOGeT2EDEkvKn60pbTBKSKAkRfzJKCofBQumqYhuyHs/HVxeC/2wimnYdmsENMVTCoec25pqyl+C0pG1uBGVdZQtysoIfR4/NGqNfoPmw9P6O5DVvCqb1ZvGogomW9+N8nKLN7XwTt4lsN9/H5t+rxDw6hkqKRwbnIy4oFrVNHOxPh
  template:
    metadata:
      name: proxmox-csi-config
      namespace: csi-proxmox
