---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: proxmox-csi-config
    creationPolicy: Owner
  data:
    - secretKey: config.yaml
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: proxmox-csi-config
