---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-credentials
  namespace: external-secrets
spec:
  encryptedData:
    clientId: AgAyXp/NZDdanAc68mmQV4znj8dWLx+TkAii8vckAkcdSU/mkxRttJNtqOVTbJvKnR90HW8011ceFzI1qCZfQO8853dEy0eLAvcsVl9f4FHAL1qjqge24dwGbJJp6GVG1/ebBgUrKohdWPBlxw/T8kra8Slcv3q5EIc+KnWkpKjarbOwPkYZDyq93jdq/+T1fLAJts4dKuYjIfI4dS1PblOZcrbwAzE2DPxwh9Xer1aTbgT0jrh3FEmjjoJmo+9pvFnIg09h+G/C8IWHQY5A7WZD1fC+8joan2yrr+JFYS3487htb1JWpt0HuvBPihHx5n4xm2fg8/WhwxCtPM5GUImLYoqmntLQJxjaiScs+jRgmyMegNfrsJp/TnxIZaTiCoVtz9+y8IdIKQ46JRMnss2NVeF8aM+FRacU01grQK+ujkKJFrisgVGwefmn5WjbPwaJgDj3wzh78AziQvQcSNPePU81cl73AwBCBm2IkPuXBQ3Wq0AEB2ZMEMc7nrQBx+RpMAMUpT6gbJ2eYRwBGTejDY//RST+tC6SgPCjBACVt/QJB4cQh4PRtYop4iYwvgaOKRSihE0Wt0muC08BvVekn/3sJnbWq7vV5iJ0REEYPmHwMp5JBkEbEYPz2P+mTz04bMjXY+cSPa2VkOfaXWn5n5Fzx8xz7cHYs2+avL9AjHqfeMK6cFvLe5MVaTWA2VmvbgZ1irzOIiNqYY2bJ98=
    clientSecret: AgCcAJEVjlvCCKTM2LzFudpSnODAYsEaG8y6kRMcILhNthB2O12flYrY5Ch0fV6Lj9teJDJNkqvZ58NxRQFH8zOUme0uztXTf8FxZT2nN7si5/tpahP4iewCOSu17PZ5Kq2GIvg5i75lpqx463JUcU4YVxAJaPRr1agO8l/fuN4YNHelQjXNjg2isF1VwMQFXGfLpdEmeBoS5E3yt6kV9/dUfOQ28abDWqHe5w2cns9vi0qEWqqLWR5x83LdUMevb1AaonYubTZdHzQ8qyImF/JPbkdPsw2xSTYDb2uHIKcebjHdl9kZ6A5BC3UcOys8i9QdDLFTlAwQldVZ2MGHPkhgAoi3PDVkb1Af8IPLpDyJLe0Jwxo7oabBbjVxlC5yjGIXXhXu3QIMs7bgIpJvPrsvM6Kv/ptHrzseT3XE2STOdpSnklSplU5CRUUVAhevzQ7zFpAvAAc8MkE2D/UOKMtYyQGiz4NxgVBR2FZxeMkoWUmESmFImefo6UN/c6lCKDk6oDtMovKLJjJaAdImgay2R16jCMTiSjEJizLudqiBfGOmcYTUs9DHDqpvfYWlAp4o8V1LVlHENNMoXKtVCUYWH2/f800AlgGx6gPy7fPrmF0lkiibHW0S5toN/EQIglor8fRyOeVREIZZ+USzvVUfiJ3JVca/BgB0CgpuDpe8JwmXmDP0425FJJFr0+BcZfiaqZ1mj136RCboFfLcEMZQcOVSjCIbifLXf9fG0Gv9qmqGcUaUZcQRHdaAerzcPC6kFdjIeKXfomtOw5iu6Av4
  template:
    metadata:
      name: infisical-credentials
      namespace: external-secrets
