operatorCrds:
  crds:
    install: true
    keep: true

operator:
  fullnameOverride: toolhive-operator
  operator:
    replicaCount: 1
    image: ghcr.io/stacklok/toolhive/operator:v0.29.1
    imagePullPolicy: IfNotPresent
    toolhiveRunnerImage: ghcr.io/stacklok/toolhive/proxyrunner:v0.29.1
    vmcpImage: ghcr.io/stacklok/toolhive/vmcp:v0.29.1
    proxyHost: 0.0.0.0
    env:
      - name: TOOLHIVE_SKIP_UPDATE_CHECK
        value: "true"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
    rbac:
      scope: namespace
      allowedNamespaces:
        - mcps
    serviceAccount:
      create: true
      automountServiceAccountToken: true
      name: toolhive-operator

registryIngress:
  enabled: true
  host: toolhive.platform.the-lab.zone
  tlsSecretName: platform-wildcard-tls
  headersMiddlewareName: default-headers
  headersMiddlewareNamespace: traefik
  serviceName: toolhive-registry-server
  servicePort: 8080

registryServer:
  fullnameOverride: toolhive-registry-server
  replicaCount: 1
  image:
    registryServerUrl: ghcr.io/stacklok/thv-registry-api:v1.4.6
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  rbac:
    scope: namespace
    allowedNamespaces:
      - mcps
  config:
    sources:
      - name: toolhive-upstream
        git:
          repository: https://github.com/stacklok/toolhive-catalog.git
          branch: main
          path: pkg/catalog/toolhive/data/registry-upstream.json
        syncPolicy:
          interval: 30m
      - name: lab-kubernetes
        kubernetes:
          namespaces:
            - mcps
        syncPolicy:
          interval: 5m
    registries:
      - name: default
        sources:
          # - toolhive-upstream
          - lab-kubernetes
    auth:
      mode: anonymous
    database:
      host: postgres.database.svc.cluster.local
      port: 5432
      user: toolhive_registry
      database: toolhive_registry
      sslMode: disable
  extraEnv:
    - name: THV_REGISTRY_DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: toolhive-registry
          key: database-password

monitoring:
  service:
    enabled: true
    name: toolhive-operator-metrics
    port: 8080
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s

secrets:
  registry:
    enabled: true
    name: toolhive-registry
    remoteRefs:
      databasePassword: /database/toolhive-registry/password
