---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-admin-token
  namespace: garage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: garage-admin-token
    creationPolicy: Owner
  data:
    - secretKey: adminToken
      remoteRef:
        key: Garage Admin Token/credential
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
