apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustdesk-keypair
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: rustdesk-keypair
    creationPolicy: Owner
  data:
    - secretKey: id_ed25519
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: rustdesk-id-ed25519
    - secretKey: id_ed25519.pub
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: rustdesk-id-ed25519-pub
