apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: forgejo-credentials
    creationPolicy: Owner
    template:
      data:
        db-password: |-
          {{ "{{ .dbPassword }}" }}
        minio-access-key: |-
          {{ "{{ .minioAccessKey }}" }}
        minio-secret-key: |-
          {{ "{{ .minioSecretKey }}" }}
        redis-url: |-
          redis://:{{ "{{ .valkeyPassword }}" }}@valkey-master.valkey.svc.cluster.local:6379/0
        redis-session-url: |-
          redis://:{{ "{{ .valkeyPassword }}" }}@valkey-master.valkey.svc.cluster.local:6379/1
        redis-queue-url: |-
          redis://:{{ "{{ .valkeyPassword }}" }}@valkey-master.valkey.svc.cluster.local:6379/2
  data:
    - secretKey: dbPassword
      remoteRef:
        key: "Forgejo Database/password"
    - secretKey: minioAccessKey
      remoteRef:
        key: "MinIO/root-user"
    - secretKey: minioSecretKey
      remoteRef:
        key: "MinIO/root-password"
    - secretKey: valkeyPassword
      remoteRef:
        key: "Valkey/password"
