---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: step-ca-provisioner-password
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: step-ca-provisioner-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: "Step CA/password"
