minio:
  mode: standalone

  deploymentUpdate:
    type: Recreate

  existingSecret: minio-credentials

  persistence:
    enabled: true
    size: 50Gi
    storageClass: proxmox-lvm

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  buckets:
    - name: forgejo
      policy: none
      purge: false
    - name: forgejo-backups
      policy: none
      purge: false      
    - name: velero
      policy: none
      purge: false
    - name: postgres-backups
      policy: none
      purge: false
    - name: assets
      policy: download
      purge: false

  consoleIngress:
    enabled: false

  metrics:
    serviceMonitor:
      enabled: true
