{{- if and .Values.secrets.grafana.enabled .Values.servers.grafana.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-grafana-credentials
  namespace: {{ .Values.namespace.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.grafana.name }}
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_SERVICE_ACCOUNT_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.secrets.grafana.remoteRefs.serviceAccountToken }}
{{- end }}
{{- if and .Values.secrets.lightrag.enabled .Values.servers.lightrag.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-lightrag-credentials
  namespace: {{ .Values.namespace.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.lightrag.name }}
    creationPolicy: Owner
  data:
    - secretKey: LIGHTRAG_API_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.secrets.lightrag.remoteRefs.apiKey }}
{{- end }}
