---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-db-url
  namespace: coder
spec:
  encryptedData:
    url: AgAA0/Yn8OZ46svavWUGfTYCDlJ7OaM4B99667RouLlfpSCrqQU4pGWqDA6aWEHXJc7Ggh9gs+d+RUn0UHYqMjtCwkblFLSwZ4YBSNXHROOHjNXINg2ociN31j3JYyI9rmJa8HWgTf11oh9Lyl2QUJNm+Yb5H3wsfAv0JYJ5ySda1wtRGWzS+/0g0vN0ueOtSzZrL5xXsH5By/06KFJBWEtTgpNpO+xeHd5EHghiHkSQPHiVFvTOjRTx26qQy35FBqlTatPQMvTBlF1INHR2WMVwpKYg0Lx/81SV/dYFP/OEhhx7OTzXWBgN1OLiUJZ9TjC7G37D2wyQkjTSD4UiAIQ6k6/C8i7ix2Zxw27a/aj6N7/bUIrjBQKUUdtCeORY0R6ODAyU95MVuebWFanF6aWZumd6rv84B2x0W63vP6M3vyjleQADA03Hd9J0n5HAxruqc/6gF0TdLFOoJqSJ7YenVXg115Lt9NYewrVoVcJbH9Y1xyT/yoURlSd022XDSRqqU5T/8TZUEjS+TANb06CKAB/eX2IGgC6CoNzUxtUetdUx1Twd1KYaj6dwwrbtfvIRuaQjtAfGa2f8WmOcwDPt9Q+M6tnZwNQsT/OtrTJojcEx+v87vV193neIZhLS2Z5VDIhHtZS47okvdzAgUZnZwrVFq0jU4HYYdqEya9PN1tF23sOttrLJcDSqib5BkS+B6zTI2BFfChP//uPNasswvM5CeRkIDTIzxYAdmxka2V1ZzmU0t6e1a7PPVY2eePVS6ALDJuG7nGYIlqj8NJMGrDH7jZbCWWksREp/A2WLUWIYwvuacdbSgeYoR2WKob3V/0UAyAKCBkO6SOKXgqR6tLJpEO0ZRBRTM8AlAin2YTo9d4aemRASGDn+fwdJy2g=
  template:
    metadata:
      name: coder-db-url
      namespace: coder
