---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-db-url
  namespace: coder
spec:
  encryptedData:
    url: AgCq+hCDTZrDRCk8KqdOCaWVQkHF/1k8ErNsdC2P2DSnTQM2lWrfypTAk7Nm6bgqyIgnJPuUvx3e/pbL1LgWvR0t89cipHOy/5rmq9uTyoah44YMoLSuN0nBKXlcFtbUAsFTvQHEGzVVSybHnRqA9bv5gYIOfzFf4to/QrKf9F4gXYU6XopmCEYoIgh9VHfp2B3LkKKaq57nbA7SucKL3gv7maHSnuLzq+cdVKBsTwQd8QAH7ypcPijW+ny7Z+1oetWqCIuYLvdG5FuwwkXP/0cQZfpIfIwg4GqjoaoILXsFujtfPV2mv2jDZsd0cIXrNby7BeNV5iNeQLXcfy7q1mME7xInLyMUgEhUSWxQpWPdlrk6GFE0Vq/KTDI5xt9KdDt2wkLMDuXC0qERkPGdxlHlzKAzLZZXkG6GkHvOBDBDxhq3L9UbQCS33udmVVtZahcoFSeERG3n8WszYzw3EnGF4MDNTm4+ZE0GEBO+BIdaqIpPVVX0gnvIubRlUWFsa6dhXEgZY97kB7L4y+8k0sv9Acra8jWvbwjSaDPSaUZRVxU7S0dvQsdq0MGmOZXr0He/qM+w6qf9r9XZ8wyN/XYXnqUdCLch9NcPuWGk/1vGLmWvvs7QFUmBKopy3I8Wnwr1wDyicCrrbeB9Ecx58/Q0PKU1Z2nFBlMqOEsuuXyefQj4hGs3dtLklw/Q6OAefF+ignABDTeymv92Py/z5110uS+oFh4Tlq1NqBtqAmn4bdDuS+Un7CrYyTp/HHtgim5MYqVwxk5HhyFGekyKHNsIOLJoP6vH+iefibb1J5tQ9PxAhv2Tzy9tUrgL+/84SwFHcPQUIh3ToR3CN9lecoQHuDyFuwoc2vkvaPdkC6FuMH6nJhVckPyGtffq35CWb1GbF7ab7byOXdFWlxqFRj+Saw==
  template:
    metadata:
      name: coder-db-url
      namespace: coder
