---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-db-url
  namespace: coder
spec:
  encryptedData:
    url: AgBH7mQe7o7TdKr8ImZbYX8+m0xKp0H5ytG0jaK59TuDzLx9eXXuYxOQM1eJmwd8Too3AobbAwVehot/OX7pxM+/I71PdiHerOUwGXDnV224MYfDkewrkrmXzaC2Nwc1Lk3N2/ZnrV+AQFjLA/PbUm7enD74EcnkklBJsizR6LdPOuW5XrbMwQes7BRjxcLofubwCy9v87oD9VUPIt3Qh55FdNqeBWYXQeRo8ocAN6eMTtXP2re0CmPCbjKn6wBI807keQWkpxM4pt1lz8Ot2nf/YT6U0N0CiO9b/A7VvkwsOi5a6aj1iHY7Puf0T45gQ2DMHoZgrYjRrZbxcr4uiPwZeJRkjKhSo6BUEf7elFUlk4vgsNbB3Ersdqsj0O3oQetUwmvmh1JsScxIgXIprobYWvkz7D486at1vP+a9f7Z3RUa3uwhTYD1EwuZz1RwnC9tZjsCc2N8rArTVtKvPxJT1g8qEYzR6Hc1dkpJPfp9Dxuz4izZINEb4sv7ra3Dm1xoF27A9PRqwcmzQQPxr3mTF8ogp9T/XuwofHP3TUXaxjAQ55F2VF1RiVez28VD1wFlz9K04S7zF1aPul/xMKXA32+PD8pHo/JIczSxN7SfunQP1evL0SBbQvKgDCYfKqLgSOKGJrv/ny+rMa03NC++VT0LD9Mq3YbKiHWojIInBVesBuJ9YnQPfa1XlWRo3ye13TmV08Gn7KD64KdkEIcmC6ET4MWnh+bupMq2QOAPh7ZI0pDkFxNOV9yj0X/OpszDFoY9tP4OlNJbonIk/9RWP4OO3TXo6VgLJjPsu7W4hmWO2v7ya+awECYy2qkS1I4oQvLTdE8K0wNvlg/JVANNoGzKIxSfxrpfb/qnD4vbR028/zg7TiWRhT7xD8C7E4Y=
  template:
    metadata:
      name: coder-db-url
      namespace: coder
