apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-credentials-work
  namespace: coder-workspaces
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: coder-credentials-work
    creationPolicy: Owner
  data:
    - secretKey: anthropic-api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /coder/work/anthropic-api-key

    - secretKey: openai-api-key
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /coder/work/openai-api-key
