metallb:
  speaker:
    tolerations:
      - operator: "Exists"
    frr:
      enabled: false


  prometheus:
    serviceAccount: vmagent-vm-stack
    namespace: monitoring
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: false
