apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_OAUTH_SECRET
      remoteRef:
        key: "Grafana Authelia OAuth/client-secret"
