external-dns:
  provider:
    name: cloudflare

  sources:
    - service
    - ingress
    - traefik-proxy
    - crd

  domainFilters:
    - the-lab.zone

  cloudflare:
    proxied: false

  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: api-token

  serviceMonitor:
    enabled: true
