---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-credentials
  namespace: "{{ .Release.Namespace }}"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: "{{ .Values.secret.name }}"
    creationPolicy: Owner
    template:
      data:
        masterkey: |-
          {{ "{{ .masterKey }}" }}
        saltkey: |-
          {{ "{{ .saltKey }}" }}
        database-username: |-
          litellm
        database-password: |-
          {{ "{{ .databasePassword }}" }}
        LITELLM_SALT_KEY: |-
          {{ "{{ .saltKey }}" }}
        OPENROUTER_API_KEY: |-
          {{ "{{ .openrouterApiKey }}" }}
        OLLAMA_API_BASE: |-
          {{ "{{ .ollamaApiBase }}" }}
        REDIS_HOST: |-
          valkey-primary.valkey.svc.cluster.local
        REDIS_PORT: |-
          "6379"
        REDIS_PASSWORD: |-
          {{ "{{ .valkeyPassword }}" }}
        REDIS_URL: |-
          redis://:{{ "{{ .valkeyPassword }}" }}@valkey-primary.valkey.svc.cluster.local:6379/4
  data:
    - secretKey: masterKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "{{ .Values.secret.remoteRefs.masterKey }}"
    - secretKey: saltKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "{{ .Values.secret.remoteRefs.saltKey }}"
    - secretKey: databasePassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "{{ .Values.secret.remoteRefs.databasePassword }}"
    - secretKey: openrouterApiKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "{{ .Values.secret.remoteRefs.openrouterApiKey }}"
    - secretKey: ollamaApiBase
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "{{ .Values.secret.remoteRefs.ollamaApiBase }}"
    - secretKey: valkeyPassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: "{{ .Values.secret.remoteRefs.valkeyPassword }}"
