apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qdrant
  namespace: qdrant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qdrant.infra.the-lab.zone`)
      kind: Rule
      services:
        - name: qdrant
          port: 6333
  tls:
    secretName: infra-wildcard-tls
