---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neo4j-credentials
  namespace: "{{ .Release.Namespace }}"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: neo4j-credentials
    creationPolicy: Owner
    template:
      data:
        NEO4J_AUTH: |-
          neo4j/{{ "{{ .neo4jPassword }}" }}
        NEO4J_USERNAME: |-
          neo4j
        NEO4J_PASSWORD: |-
          {{ "{{ .neo4jPassword }}" }}
        minio-access-key: |-
          {{ "{{ .minioAccessKey }}" }}
        minio-secret-key: |-
          {{ "{{ .minioSecretKey }}" }}
  data:
    - secretKey: neo4jPassword
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /neo4j/password
    - secretKey: minioAccessKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /minio/root-user
    - secretKey: minioSecretKey
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /minio/root-password
