---
# Syncs the Authentik OIDC client secret from 1Password into a Secret
# that ArgoCD's Dex connector references via $argocd-oidc:dex.authentik.clientSecret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: argocd-oidc
    creationPolicy: Owner
  data:
    - secretKey: dex.authentik.clientSecret
      remoteRef:
        key: "ArgoCD Authentik OAuth/client-secret"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
