---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: context-forge
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      middlewares:
        - name: {{ .Values.ingress.headersMiddlewareName }}
          namespace: {{ .Values.ingress.headersMiddlewareNamespace }}
      services:
        - name: context-forge-mcpgateway
          port: 80
  tls:
    secretName: {{ .Values.ingress.tlsSecretName }}
