apiVersion: v2
name: victoria-stack
version: 0.0.0
dependencies:
  - name: victoria-metrics-k8s-stack
    alias: metrics
    version: "0.70.0"
    repository: https://victoriametrics.github.io/helm-charts/
  - name: victoria-logs-single
    alias: logs
    version: "0.11.26"
    repository: https://victoriametrics.github.io/helm-charts/
  - name: victoria-logs-collector
    alias: log-collectors
    version: "0.2.9"
    repository: https://victoriametrics.github.io/helm-charts/
  - name: victoria-traces-single
    alias: traces
    version: "0.0.6"
    repository: https://victoriametrics.github.io/helm-charts/
