# Allows Argo CD (application controller) to read the bootstrap secret referenced by
# ClusterSecretStore, so Argo CD can resolve/validate the resource without "secret not found".
# The secret itself (onepassword-credentials) is created manually; this only grants read access.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-read-onepassword-credentials
  namespace: external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["onepassword-credentials"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-read-onepassword-credentials
  namespace: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-read-onepassword-credentials
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
