# This ClusterSecretStore connects ESO to 1Password.
#
# Before this can work, you need to bootstrap the 1Password token once:
#
#   kubectl create namespace external-secrets
#   kubectl create secret generic onepassword-credentials \
#     --from-literal=token=<your-1password-service-account-token> \
#     -n external-secrets
#
# After that, any ExternalSecret in any namespace can reference this store:
#
#   apiVersion: external-secrets.io/v1beta1
#   kind: ExternalSecret
#   spec:
#     secretStoreRef:
#       name: onepassword
#       kind: ClusterSecretStore
#     data:
#       - secretKey: api-key
#         remoteRef:
#           key: homelab/truenas-api-key
#           property: credential

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: ""
      vaults:
        homelab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-credentials
            key: token
            namespace: external-secrets
