velero:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.14.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

  credentials:
    existingSecret: velero-s3-credentials

  configuration:
    backupStorageLocation:
      - name: default
        provider: aws
        bucket: velero
        default: true
        config:
          region: us-east-1
          s3ForcePathStyle: "true"
          s3Url: http://10.40.1.20:9000

  schedules:
    daily-full-backup:
      schedule: "0 3 * * *"
      template:
        ttl: "360h" # 15 days
        storageLocation: default
        includedNamespaces:
          - "*"
        excludedNamespaces:
          - kube-system
          - kube-public
          - kube-node-lease

  kubectl:
    image:
      repository: docker.io/bitnamilegacy/kubectl
      tag: "1.33.4"

  snapshotsEnabled: false
  deployNodeAgent: false

vui:
  global:
    veleroNamespace: velero
    clusterName: platform

  auth:
    enabled: false

  exposure:
    mode: ingress
    ingress:
      ingressClassName: traefik
      spec:
        tls:
          - hosts:
              - velero.platform.the-lab.zone
