---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-driver-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: truenas-driver-config
    creationPolicy: Owner
  data:
    - secretKey: driver-config-file.yaml
      remoteRef:
        key: truenas-driver-config
