zot:
  replicaCount: 1

  persistence: true
  pvc:
    create: true
    storage: 50Gi
    storageClassName: proxmox-lvm

  serviceMonitor:
    enabled: true

  mountConfig: true

  configFiles:
    config.json: |-
      {
        "storage": { "rootDirectory": "/var/lib/registry" },
        "http": { "address": "0.0.0.0", "port": "5000" },
        "log": { "level": "info" },
        "extensions": {
          "search": {
            "enable": true
          },
          "ui": {
            "enable": true
          },
          "sync": {
            "enable": true,
            "registries": [
              {
                "urls": ["https://registry-1.docker.io"],
                "onDemand": true,
                "tlsVerify": true,
                "content": [
                  {
                    "prefix": "**",
                    "destination": "/dockerhub"
                  }
                ]
              },
              {
                "urls": ["https://ghcr.io"],
                "onDemand": true,
                "tlsVerify": true,
                "content": [
                  {
                    "prefix": "**",
                    "destination": "/ghcr"
                  }
                ]
              },
              {
                "urls": ["https://code.forgejo.org"],
                "onDemand": true,
                "tlsVerify": true,
                "content": [
                  {
                    "prefix": "**",
                    "destination": "/forgejo"
                  }
                ]
              }
            ]
          }
        }
      }
